CREATE TABLE `submissions` (
	`id` text PRIMARY KEY NOT NULL,
	`author_name` text NOT NULL,
	`author_email` text NOT NULL,
	`age_band` text NOT NULL,
	`guardian_email` text,
	`school_or_organization` text,
	`country_or_region` text,
	`manuscript_title` text NOT NULL,
	`discipline` text NOT NULL,
	`abstract` text NOT NULL,
	`word_count` integer NOT NULL,
	`origin_note` text NOT NULL,
	`ai_disclosure` text NOT NULL,
	`manuscript_key` text NOT NULL,
	`manuscript_filename` text NOT NULL,
	`manuscript_content_type` text NOT NULL,
	`status` text DEFAULT 'received' NOT NULL,
	`original_work_confirmed` integer NOT NULL,
	`privacy_confirmed` integer NOT NULL,
	`guardian_confirmed` integer DEFAULT false NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
