CREATE TABLE IF NOT EXISTS `review_assignments` (
	`id` text PRIMARY KEY NOT NULL,
	`submission_id` text NOT NULL,
	`reviewer_name` text NOT NULL,
	`reviewer_email` text NOT NULL,
	`reviewer_application_id` text,
	`status` text DEFAULT 'invited' NOT NULL,
	`due_at` text,
	`conflict_confirmed` integer DEFAULT false NOT NULL,
	`confidentiality_confirmed` integer DEFAULT false NOT NULL,
	`question_score` integer,
	`context_score` integer,
	`method_score` integer,
	`evidence_score` integer,
	`clarity_score` integer,
	`integrity_score` integer,
	`recommendation` text,
	`comments` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`submitted_at` text
);
